name: Ubuntu CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get -qq update
        sudo apt install libwayland-dev libxrandr-dev libx11-xcb-dev libmirclient-dev libxkbcommon-dev

    - name: Setup Vulkan Environment
      working-directory: ./tools/vulkan_development
      run: bash ./vulkan-setup.sh --no-vulkan-tools

    - name: Configure CMake
      run: |
        source ./tools/vulkan_development/setup-vulkan-development-env.sh
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
