name: Ubuntu CI - Vulkan from SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  Vulkan_INCLUDE_DIRS: /usr/include/
  Vulkan_GLSLANG_VALIDATOR_EXECUTABLE: /usr/bin/glslangValidator
  VK_LAYER_PATH: /etc/vulkan/explicit_layer.d
  Vulkan_LIBRARIES: /usr/lib/x86_64-linux-gnu/libvulkan.so;/usr/lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vulkan SDK
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.198-focal.list https://packages.lunarg.com/vulkan/1.2.198/lunarg-vulkan-1.2.198-focal.list
        sudo apt update
        sudo apt install vulkan-sdk

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
