name: Ubuntu CI - Vulkan from Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  Vulkan_INCLUDE_DIRS: /usr/include/
  VK_LAYER_PATH: /etc/vulkan/explicit_layer.d
  Vulkan_LIBRARIES: /usr/lib/x86_64-linux-gnu/libvulkan.so

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get -qq update
        sudo apt install libwayland-dev libxrandr-dev libx11-xcb-dev libmirclient-dev libxkbcommon-dev libvulkan-dev

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
